/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/tasks': {
    /** Получить все задачи */
    get: {
      parameters: {
        query?: {
          /**
           * @description Фильтр по важности задач
           * @example true
           */
          isImportant?: boolean;
          /**
           * @description Поиск задач по названию (регистронезависимый)
           * @example Задача
           */
          name_like?: string;
          /**
           * @description Фильтр по завершенности задач
           * @example false
           */
          isCompleted?: boolean;
        };
      };
      responses: {
        /** @description Успешный ответ */
        200: {
          content: {
            'application/json': components['schemas']['Task'][];
          };
        };
        /** @description Ошибка сервера */
        500: {
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    /** Создать новую задачу */
    post: {
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateTask'];
        };
      };
      responses: {
        /** @description Задача создана */
        201: {
          content: {
            'application/json': components['schemas']['Task'];
          };
        };
        /** @description Неверные данные */
        400: {
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Ошибка сервера */
        500: {
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
  };
  '/tasks/{id}': {
    /** Получить задачу по ID */
    get: {
      parameters: {
        path: {
          /** @description ID задачи */
          id: number;
        };
      };
      responses: {
        /** @description Успешный ответ */
        200: {
          content: {
            'application/json': components['schemas']['Task'];
          };
        };
        /** @description Неверный ID */
        400: {
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Задача не найдена */
        404: {
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Ошибка сервера */
        500: {
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    /** Удалить задачу */
    delete: {
      parameters: {
        path: {
          /** @description ID задачи */
          id: number;
        };
      };
      responses: {
        /** @description Задача удалена */
        200: {
          content: {
            'application/json': components['schemas']['Task'];
          };
        };
        /** @description Неверный ID */
        400: {
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Задача не найдена */
        404: {
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Ошибка сервера */
        500: {
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    /** Обновить задачу */
    patch: {
      parameters: {
        path: {
          /** @description ID задачи */
          id: number;
        };
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateTask'];
        };
      };
      responses: {
        /** @description Задача обновлена */
        200: {
          content: {
            'application/json': components['schemas']['Task'];
          };
        };
        /** @description Неверные данные */
        400: {
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Задача не найдена */
        404: {
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Ошибка сервера */
        500: {
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Task: {
      /** @example 1 */
      id?: number;
      /** @example Сделать домашку по запросам */
      name?: string;
      /** @example Использовать патерн controller */
      info?: string;
      /** @example true */
      isImportant?: boolean;
      /** @example false */
      isCompleted?: boolean;
    };
    CreateTask: {
      /** @example Новая задача */
      name: string;
      /** @example Описание задачи */
      info?: string;
      /** @example false */
      isImportant?: boolean;
      /** @example false */
      isCompleted?: boolean;
    };
    UpdateTask: {
      /** @example Обновленное название */
      name?: string;
      /** @example Обновленное описание */
      info?: string;
      /** @example true */
      isImportant?: boolean;
      /** @example true */
      isCompleted?: boolean;
    };
    Error: {
      /** @example Сообщение об ошибке */
      error?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
